//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class _AnnualLeavePlan
    {
        [Key]

        public int ALPID { get; set; }

         [Required(ErrorMessage = "Year is Leave Category.")]
        public Nullable<int> LeaveCategoryID { get; set; }

        [Required(ErrorMessage = "Year is Required.")]
        public Nullable<int> Year { get; set; }
        public Nullable<int> TotalLeaveMonth { get; set; }

         [Required(ErrorMessage = "Total Leave Days is Required.")]
        public Nullable<int> TotalLeaveDays { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
       // public Nullable<string> LeaveCategoryName { get; set; }
     }
}
