//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class _FixedAllowanceCancel
    {
        [Key]
        public int FACID { get; set; }
        public Nullable<int> FixedAllowanceDetailId { get; set; }
        [Required(ErrorMessage = "Cancel Authority cann't Null")]
        public string CancelAuthority { get; set; }
        [Required(ErrorMessage = "Cancel Authority cann't Null")]
        public Nullable<System.DateTime> CancelAuthorityDate { get; set; }
        public string Remark { get; set; }
        public string Rank { get; set; }
        public string AllowanceName { get; set; }
        public string AllowanceCategory { get; set; }   
        public Nullable<System.DateTime> EffectiveDate { get; set; }        
        public Nullable<System.DateTime> CampAuthorityDate{ get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CampAuthority { get; set; }
        public string SurName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> CancelAuthorityEffectiveDate { get; set; }

        public virtual _FixedAllowanceDetail _FixedAllowanceDetail { get; set; }
    }
}
