//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allowance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Allowance()
        {
            this.AllowanceItemCodes = new HashSet<AllowanceItemCode>();
            this.EDCS_AllowanceValue = new HashSet<EDCS_AllowanceValue>();
            this.FixedAllowanceDetails = new HashSet<FixedAllowanceDetail>();
        }
    
        public int ALWID { get; set; }
        public Nullable<int> SECID { get; set; }
        public string AllowanceName { get; set; }
        public string AllowanceShortName { get; set; }
        public Nullable<int> IsOfficer { get; set; }
        public Nullable<int> IsOR { get; set; }
        public Nullable<int> AllowanceDuration { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CalculateType { get; set; }
        public Nullable<int> ProcessType { get; set; }
        public Nullable<int> ReferenceItem { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> AllowanceTypeId { get; set; }
    
        public virtual LocationType LocationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllowanceItemCode> AllowanceItemCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDCS_AllowanceValue> EDCS_AllowanceValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedAllowanceDetail> FixedAllowanceDetails { get; set; }
    }
}
