//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowanceValueRank
    {
        public int AVRID { get; set; }
        public Nullable<int> AllowanceValueID { get; set; }
        public Nullable<int> RankID { get; set; }
        public Nullable<decimal> RankAllowanceValue { get; set; }
    }
}
