//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CivilStatusSpouseDetail
    {
        public int CSSPDID { get; set; }
        public Nullable<int> CivilStatusHeaderID { get; set; }
        public string SpouseName { get; set; }
        public Nullable<int> SpouseStatusId { get; set; }
        public string SpousNICNo { get; set; }
        public string SpousOccupation { get; set; }
        public string SpousOffcialAddress { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public string CreateIpAddess { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
