//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CivilStatusWidowDetail
    {
        public int CSWDID { get; set; }
        public Nullable<int> CivilStatusHeaderID { get; set; }
        public string DeathCertificateNoOfSpouse { get; set; }
        public string LivingInAndOutStatus { get; set; }
        public string NOKChangeTo { get; set; }
        public Nullable<System.DateTime> DateofDecease { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
        public string CreateIpAddess { get; set; }
    }
}
