//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisturbanceAmount
    {
        public decimal MrriedPostedOfficer { get; set; }
        public decimal MarriedAttachedOfficer { get; set; }
        public decimal BachelorAttachedOfficer { get; set; }
        public decimal MarriedPostedAirman { get; set; }
        public decimal MarriedAttachedAirman { get; set; }
        public decimal BachelorAttachedAirman { get; set; }
    }
}
