//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division1
    {
        public string LocationID { get; set; }
        public string DivisionID { get; set; }
        public string DivisionType { get; set; }
        public string DivisionName { get; set; }
        public string OfficeCommand { get; set; }
        public int NoOfPersonnel { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUser { get; set; }
    }
}
