//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DutyLocation
    {
        public int DutyLocId { get; set; }
        public string Camp { get; set; }
        public string CampDutyLocation { get; set; }
        public int Active { get; set; }
    }
}
