//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDCS_ProcessedTransactions
    {
        public long AutoID { get; set; }
        public int ProcessTypeID { get; set; }
        public long ProcessHeaderID { get; set; }
        public int ReferanceTableID { get; set; }
        public int ItemCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Authority { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string RecordOriginatedLocation { get; set; }
        public Nullable<int> ItemOrigin { get; set; }
        public string ProcessedUser { get; set; }
        public Nullable<System.DateTime> ProcessedDateTime { get; set; }
        public string ProcessedMachine { get; set; }
        public Nullable<int> IsForwardedtoPayroll { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
