//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDCS_AllowanceValueRank
    {
        public int AVRID { get; set; }
        public Nullable<int> AllowanceID { get; set; }
        public Nullable<int> AllowanceCategoryId { get; set; }
        public Nullable<int> RankID { get; set; }
        public Nullable<decimal> AllowanceValue { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Authority { get; set; }
        public Nullable<int> Status { get; set; }
        public string MonthlyDaily { get; set; }
    }
}
