//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDCS_ProcessHeader
    {
        public int ProcessHeaderID { get; set; }
        public Nullable<int> ProcessTypeID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> PayYear { get; set; }
        public Nullable<int> PayMonth { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMachine { get; set; }
    }
}
