//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDCS_AllowanceValue
    {
        public int AVID { get; set; }
        public Nullable<int> AllowanceID { get; set; }
        public Nullable<int> AllowanceCategoryId { get; set; }
        public Nullable<decimal> OfficerAmount { get; set; }
        public Nullable<decimal> ORAmount { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Authority { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Allowance Allowance { get; set; }
    }
}
