//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpasLocation
    {
        public string LocationID { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> NoOfDivisions { get; set; }
        public Nullable<int> NoOfPersonnel { get; set; }
        public string Description { get; set; }
        public string DBName { get; set; }
        public string SystemURL { get; set; }
        public Nullable<int> OCLIDSeriesStart { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public string HostID { get; set; }
        public string LocAddress { get; set; }
        public string TelephoneNo { get; set; }
        public string FaxNo { get; set; }
        public string NameOfCO { get; set; }
        public string RankofCO { get; set; }
        public string Appointment { get; set; }
        public string NameOfOCL { get; set; }
        public string RankofOCL { get; set; }
    }
}
