//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F121AllDetails
    {
        public string ServiceNo { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfEnlist { get; set; }
        public int ChargeNo { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public string CreateLocation { get; set; }
        public Nullable<int> IsOptedCM { get; set; }
        public Nullable<int> IsRemanForCM { get; set; }
        public Nullable<int> IsSec40Compiled { get; set; }
        public Nullable<int> OcpsProcess { get; set; }
        public string ChargeNo2 { get; set; }
        public Nullable<int> OicProcess { get; set; }
        public string OffenceName { get; set; }
        public string OffenceWASO { get; set; }
        public string OffencePlace { get; set; }
        public Nullable<System.DateTime> OffenceDate { get; set; }
        public string OffenceSection { get; set; }
        public string Punishment { get; set; }
        public string PunishmentDescription { get; set; }
        public Nullable<int> PunishmentID { get; set; }
        public Nullable<System.DateTime> PunishDate { get; set; }
        public Nullable<int> AwardedBy { get; set; }
        public string Appointment { get; set; }
        public Nullable<int> No { get; set; }
        public string DetailsOfDocument { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
    }
}
