//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F1250
    {
        public string ActiveNo { get; set; }
        public string SNo { get; set; }
        public int Rank { get; set; }
        public string F12501 { get; set; }
        public string Initials { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Branch_Trade { get; set; }
        public string NICNo { get; set; }
        public string Sex { get; set; }
        public Nullable<decimal> Feet { get; set; }
        public Nullable<decimal> Inch { get; set; }
        public Nullable<int> ColourofHair { get; set; }
        public Nullable<int> ColourofEyes { get; set; }
        public Nullable<int> BloodGroup { get; set; }
        public string BirthMark { get; set; }
        public Nullable<System.DateTime> Expire_Date { get; set; }
        public Nullable<System.DateTime> EXPIRES_DTE { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Service_Type { get; set; }
        public Nullable<int> Service_Status { get; set; }
        public string ServicingStatus { get; set; }
        public int SVCType { get; set; }
        public string Expr1 { get; set; }
        public string NICNo_New { get; set; }
        public string DTE_ISU { get; set; }
        public string BATCH_NO { get; set; }
        public string SER_NO_CARD { get; set; }
        public string NO_OF_CARDS { get; set; }
        public Nullable<System.DateTime> DateOfEnlist { get; set; }
        public string RNK_NAME { get; set; }
        public string RptShortName { get; set; }
        public string Posted_Location { get; set; }
        public Nullable<System.DateTime> ID_EXP_DAT { get; set; }
        public string Posted_Formation { get; set; }
        public string LivingIn_Out { get; set; }
        public string DivisionName { get; set; }
    }
}
