//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F252OffenceInfo
    {
        public int OIID { get; set; }
        public int OffenceTypeId { get; set; }
        public int CHID { get; set; }
        public string OffenceWASO { get; set; }
        public string OffencePlace { get; set; }
        public Nullable<System.DateTime> OffenceDate { get; set; }
        public string OffenceSection { get; set; }
        public Nullable<int> PunishableSection { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public string CreatedIP { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public string ModifiedIP { get; set; }
        public Nullable<short> Active { get; set; }
    }
}
