//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedAllowanceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FixedAllowanceDetail()
        {
            this.FixedAllowanceCancels = new HashSet<FixedAllowanceCancel>();
        }
    
        public int FADID { get; set; }
        public Nullable<int> ServiceCategoryId { get; set; }
        public Nullable<int> AllowanceCategoryID { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public Nullable<int> AllowanceId { get; set; }
        public Nullable<int> FullHalfPay { get; set; }
        public string Sno { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CampAuthority { get; set; }
        public Nullable<System.DateTime> CampAuthorityDate { get; set; }
        public string CancelReferanceNo { get; set; }
        public Nullable<int> CeasedId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsProcessed { get; set; }
        public string EstablishmentId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> AllowanceTypeId { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
    
        public virtual Allowance Allowance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedAllowanceCancel> FixedAllowanceCancels { get; set; }
    }
}
