//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCodeList
    {
        public int CID { get; set; }
        public Nullable<int> IteamCode { get; set; }
        public string IteamShortName { get; set; }
        public string IteamLongName { get; set; }
        public string IteamType { get; set; }
    }
}
