//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveHeader
    {
        public int LHID { get; set; }
        public Nullable<int> ServiceCategoryId { get; set; }
        public string Sno { get; set; }
        public Nullable<int> LeaveCategoryId { get; set; }
        public string EstablishmentId { get; set; }
        public string DeivisionId { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<int> PrivilegeLeave { get; set; }
        public Nullable<int> AnnualLeave { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Authority { get; set; }
        public Nullable<int> PorStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> IsProcessed { get; set; }
        public Nullable<int> LivingStatus { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public string ProcessedBy { get; set; }
    
        public virtual LeaveCategory LeaveCategory { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
    }
}
