//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveDetail
    {
        public int LDID { get; set; }
        public Nullable<int> LeaveHeaderId { get; set; }
        public Nullable<int> PrivilegeLeave { get; set; }
        public Nullable<int> CasualLeave { get; set; }
        public Nullable<int> AnnualLeave { get; set; }
        public Nullable<int> LeaveLeave { get; set; }
        public Nullable<decimal> Weekend { get; set; }
        public Nullable<int> PublicHoliday { get; set; }
        public Nullable<int> ReEngagementLeave { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
