//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivingStatu
    {
        public int LSID { get; set; }
        public string LivingStatusShortName { get; set; }
        public string LivingStatusName { get; set; }
        public string Remark { get; set; }
    }
}
