//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivingInOutHeader
    {
        public int LIOHID { get; set; }
        public Nullable<long> Sno { get; set; }
        public Nullable<int> LivingStatusID { get; set; }
        public string Location { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public string RefNo { get; set; }
        public string Authority { get; set; }
        public Nullable<int> IsNOKChange { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<short> PreviousReject { get; set; }
        public string RejectAuth { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> RecordCount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> IsProcessed { get; set; }
    }
}
