//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marriage
    {
        public string MarriageID { get; set; }
        public string SNo { get; set; }
        public string MarriedCertificateID { get; set; }
        public string SpouseName { get; set; }
        public string SpouseNICNO { get; set; }
        public string SpouseOccupation { get; set; }
        public string SpouseOffAdress { get; set; }
        public Nullable<System.DateTime> MarriedDate { get; set; }
        public string MarriedPlace { get; set; }
        public Nullable<int> MarriedStatus { get; set; }
        public Nullable<int> IsArmedService { get; set; }
        public Nullable<int> ArmedService { get; set; }
        public string SpouseRank { get; set; }
        public string SpouseServiceNo { get; set; }
        public string AuthRef { get; set; }
        public string MarriagePOR { get; set; }
        public Nullable<int> POROccuranceNo { get; set; }
        public Nullable<System.DateTime> DivorceDate { get; set; }
        public string DivorcePOR { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
        public string DeathPOR { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsServiceWedding { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMachine { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMachine { get; set; }
        public Nullable<int> MarriedCertificateUpdateStatus { get; set; }
    }
}
