//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOKChangeDetail
    {
        public int NOKCDID { get; set; }
        public Nullable<int> NOKChangeHeadrerID { get; set; }
        public string NOKAddress { get; set; }
        public string NOKName { get; set; }
        public string NOKChangeTo { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string GSDivision { get; set; }
        public string NearestTown { get; set; }
        public string PoliceStation { get; set; }
        public string PostOffice { get; set; }
        public string Authority { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
        public string CreateIpAddess { get; set; }
    }
}
