//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P2_PostCode
    {
        public Nullable<int> DIST_CODE { get; set; }
        public string POST_NAME { get; set; }
        public string CATG { get; set; }
        public string POST_CODE { get; set; }
    }
}
