//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class P3HRMS : DbContext
    {
        public P3HRMS()
            : base("name=P3HRMS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Marriage> Marriages { get; set; }
        public virtual DbSet<NOK_Change_Details> NOK_Change_Details { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<ServicePersonnelProfile> ServicePersonnelProfiles { get; set; }
        public virtual DbSet<ServicePersonnelProfileNew> ServicePersonnelProfileNews { get; set; }
        public virtual DbSet<Sec_Duty_Details> Sec_Duty_Details { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
    }
}
