//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORFlowGroup
    {
        public int PFGUD { get; set; }
        public string PORCode { get; set; }
        public string PORName { get; set; }
        public string FlowGroupP3 { get; set; }
        public string FlowGroupP2 { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
