//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorLeaveOccurrenceHeader
    {
        public PorLeaveOccurrenceHeader()
        {
            this.PorLeaveOccurrenceDetails = new HashSet<PorLeaveOccurrenceDetail>();
        }
    
        public int PLOHID { get; set; }
        public Nullable<int> PorOccurrenceMasterId { get; set; }
        public Nullable<int> LivingStatusId { get; set; }
        public Nullable<int> MovementStatusId { get; set; }
        public Nullable<int> PayStatusId { get; set; }
        public Nullable<int> RationStatusId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Authority { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Active { get; set; }
        public string IpAddress { get; set; }
    
        //public virtual PayStatu PayStatu { get; set; }
        public virtual ICollection<PorLeaveOccurrenceDetail> PorLeaveOccurrenceDetails { get; set; }
       // public virtual PorOccurrenceMaster PorOccurrenceMaster { get; set; }
        //public virtual RationStatu RationStatu { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
    }
}
