//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorLeaveOccurrenceDetail
    {
        public int PLODID { get; set; }
        public int PorLeaveOccurrenceHeaderId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public Nullable<double> TotalDays { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Active { get; set; }
        public string IpAddress { get; set; }
    
        public virtual PorLeaveOccurrenceHeader PorLeaveOccurrenceHeader { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
        public virtual UserInfo UserInfo2 { get; set; }
        public virtual UserInfo UserInfo3 { get; set; }
    }
}
