//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorMovementOccurrence
    {
        public int PMOID { get; set; }
        public Nullable<int> PorOccurrenceMasterId { get; set; }
        public string FromEstablishmentId { get; set; }
        public string FromFormationId { get; set; }
        public string ToEstablishmentId { get; set; }
        public string ToFormationId { get; set; }
        public Nullable<int> MovementStatusId { get; set; }
        public Nullable<int> MovementConditionId { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Active { get; set; }
        public string IpAddress { get; set; }
    
        
        //public virtual PorOccurrenceMaster PorOccurrenceMaster { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
    }
}
