//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorObject
    {
        public int OID { get; set; }
        public Nullable<int> RID { get; set; }
        public string Objects_Name { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
