//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessHeader
    {
        public ProcessHeader()
        {
            this.ProcessDetails = new HashSet<ProcessDetail>();
        }
    
        public int PHID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> ProcessStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual ICollection<ProcessDetail> ProcessDetails { get; set; }
    }
}
