//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsnContactHeader
    {
        public int PCHID { get; set; }
        public Nullable<long> Sno { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public string RefNo { get; set; }
        public string Location { get; set; }
        public Nullable<int> MasSubCatID { get; set; }
        public string Authority { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<short> ISProcessed { get; set; }
        public Nullable<short> PreviousReject { get; set; }
        public string RejectAuth { get; set; }
        public Nullable<int> RecordCount { get; set; }
        public Nullable<short> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
    }
}
