//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsnChildDetail
    {
        public int PCDID { get; set; }
        public Nullable<int> PsnConHeaderID { get; set; }
        public Nullable<int> PsnBirthHeaderID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<int> MasterSubCatID { get; set; }
        public Nullable<short> Gender { get; set; }
        public string ChildFullName { get; set; }
        public string ChildFullNameWithInitial { get; set; }
        public string District { get; set; }
        public string BirthCertificateNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string BirthPlace { get; set; }
        public string DeathCertificateNo { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
        public Nullable<short> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
    }
}
