//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rank
    {
        public int RANK1 { get; set; }
        public string RNK_NAME { get; set; }
        public Nullable<int> RANK_TYPE { get; set; }
        public string SHORT_NAME { get; set; }
        public string LONG_NAME { get; set; }
    }
}
