//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RationAllowenceCharge
    {
        public int RAID { get; set; }
        public Nullable<decimal> OffAmmount { get; set; }
        public Nullable<decimal> OtherRankAmmount { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
