//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_Duty_Details
    {
        public string SecDutyID { get; set; }
        public string SNo { get; set; }
        public int Appointment { get; set; }
        public int SecDutyLocation { get; set; }
        public Nullable<System.DateTime> Duty_Allocate_Date { get; set; }
        public string Base { get; set; }
        public string AuthReff { get; set; }
        public Nullable<int> DutyStatus { get; set; }
        public Nullable<System.DateTime> DutyEndDate { get; set; }
        public string Remarks { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedMachine { get; set; }
        public string ModifiedMachine { get; set; }
        public Nullable<int> Status { get; set; }
        public string Area { get; set; }
    }
}
