//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecondaryDutyDetail
    {
        public int SDDID { get; set; }
        public Nullable<int> SecondaryDutyHeaderID { get; set; }
        public string AreaForResponsibility { get; set; }
        public string Appointment { get; set; }
        public Nullable<int> DutyStatus { get; set; }
        public Nullable<System.DateTime> WithEffectDate { get; set; }
        public Nullable<System.DateTime> CeasedDate { get; set; }
        public Nullable<int> TakingOverSno { get; set; }
        public Nullable<System.DateTime> TakingOverWithEffectDate { get; set; }
        public Nullable<int> TakingOverDutyStatus { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
        public string CreateIpAddess { get; set; }
    }
}
