//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecondaryDutyHeader
    {
        public int SDHID { get; set; }
        public Nullable<long> Sno { get; set; }
        public string Location { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public Nullable<System.DateTime> WFDate { get; set; }
        public string Authority { get; set; }
        public string RefNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
        public string CreateIpAddess { get; set; }
        public Nullable<int> OicProces { get; set; }
    }
}
