//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Type
    {
        public int SVCType { get; set; }
        public string Service_TypeFull { get; set; }
        public Nullable<int> IsOfficer { get; set; }
    }
}
