//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePersonnelProfile
    {
        public string SNo { get; set; }
        public string SvcID { get; set; }
        public string FingerID { get; set; }
        public string ServiceNo { get; set; }
        public string TANo { get; set; }
        public string ActiveNo { get; set; }
        public string F1250 { get; set; }
        public string RR_No { get; set; }
        public int Rank { get; set; }
        public Nullable<int> IntakeType { get; set; }
        public string Intake { get; set; }
        public Nullable<int> Branch_Trade { get; set; }
        public string Trade_Group { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string Initials { get; set; }
        public Nullable<int> Service_Type { get; set; }
        public Nullable<int> Service_Status { get; set; }
        public string Remark { get; set; }
        public byte[] ProfilePicture { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> Date_of_Enlist { get; set; }
        public Nullable<System.DateTime> Expire_Date { get; set; }
        public Nullable<System.DateTime> Date_of_PresentRank { get; set; }
        public string Posted_Location { get; set; }
        public string Posted_Formation { get; set; }
        public string Current_Location { get; set; }
        public string Current_Formation { get; set; }
        public string Posted_Status { get; set; }
        public string LivingIn_Out { get; set; }
        public Nullable<int> Status { get; set; }
        public string Sex { get; set; }
        public string NICNo_New { get; set; }
        public string Marriage_Status { get; set; }
        public Nullable<int> MedCat { get; set; }
        public byte[] Picture { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMachine { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMachine { get; set; }
        public string NICNo { get; set; }
        public string HashSno { get; set; }
        public string Appoinment { get; set; }
        public Nullable<int> MedicalBoardStatus { get; set; }
        public string SvcDocLocation { get; set; }
        public string LivingIn_Out_PorNo { get; set; }
    }
}
