//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestVw
    {
        public int FADID { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public string ServiceNo { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public Nullable<int> AllowanceId { get; set; }
        public Nullable<int> AllowanceCategoryID { get; set; }
        public string CampAuthority { get; set; }
        public Nullable<System.DateTime> CampAuthorityDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> RecordStatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> RankID { get; set; }
        public string AllowanceName { get; set; }
        public string Service_Type { get; set; }
        public Nullable<int> FMSID { get; set; }
        public Nullable<int> Active { get; set; }
        public string EstablishmentId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
