//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.LeaveHeaders = new HashSet<LeaveHeader>();
            this.LeaveHeaders1 = new HashSet<LeaveHeader>();
            this.SystemLogs = new HashSet<SystemLog>();
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public int UID { get; set; }
        public int RoleId { get; set; }
        public string LocationId { get; set; }
        public string DivisionId { get; set; }
        public Nullable<int> LocationType { get; set; }
        public Nullable<int> SecurityQuestionId { get; set; }
        public string SecurityQuestionAnswer { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ServiceNo { get; set; }
        public string UserRoleCategory { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveHeader> LeaveHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveHeader> LeaveHeaders1 { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemLog> SystemLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDetail> UserDetails { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
