//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int UPID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AccessLocationId { get; set; }
        public Nullable<bool> AllowVAF { get; set; }
        public Nullable<bool> AllowRAF { get; set; }
        public Nullable<bool> CreateRecord { get; set; }
        public Nullable<bool> ForwardRecord { get; set; }
        public Nullable<bool> RejectRecord { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
