//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_CurrentUserRoleMarried
    {
        public int FSCSID { get; set; }
        public Nullable<int> CivilStatusHeaderID { get; set; }
        public Nullable<int> RecordStatusID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FlowManagementStatusID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> RejectStatus { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
        public Nullable<int> SubmitStatus { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string Location { get; set; }
        public string Authority { get; set; }
        public string RefNo { get; set; }
        public Nullable<int> HeaderActive { get; set; }
        public string ServiceNo { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public string CategoryName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
