//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_CivliStatusReject
    {
        public int CSHID { get; set; }
        public Nullable<int> CivilStatusHeaderID { get; set; }
        public Nullable<long> Sno { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string Location { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public string RefNo { get; set; }
        public string Authority { get; set; }
        public Nullable<int> Active { get; set; }
        public string CategoryName { get; set; }
        public string CategoryCode { get; set; }
        public string SpouseName { get; set; }
        public Nullable<int> CSMDID { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public string MarriageCertificateNo { get; set; }
        public string RegistarOfficeLocation { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<System.DateTime> DivorceDtae { get; set; }
        public string Place { get; set; }
        public string CourseCaseNo { get; set; }
        public Nullable<System.DateTime> DateOfCase { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<int> CSWDID { get; set; }
        public Nullable<System.DateTime> DateofDecease { get; set; }
        public string DeathCertificateNoOfSpouse { get; set; }
        public string NOKAddress { get; set; }
        public string NOKName { get; set; }
        public string NOKChangeTo { get; set; }
        public string Remarks { get; set; }
        public string District { get; set; }
        public string GSDivision { get; set; }
        public string NearestTown { get; set; }
        public string PoliceStation { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public string ServiceNo { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
        public Nullable<int> RejectStatus { get; set; }
        public Nullable<int> SubmitStatus { get; set; }
        public int FMSID { get; set; }
        public int FSCSID { get; set; }
    }
}
