//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_CurrentAttachment
    {
        public string Ser_No { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public string Branch { get; set; }
        public System.DateTime Posted_Date { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Location { get; set; }
        public string DivisionName { get; set; }
        public string AppointName { get; set; }
        public Nullable<int> SENIORITY { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
