//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_FAEligibleList
    {
        public string ServiceNo { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public string AllowanceName { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string SNo { get; set; }
        public int ELFAID { get; set; }
        public string PostedLocation { get; set; }
        public Nullable<int> RankID { get; set; }
        public Nullable<int> AllowanceId { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
