//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_FlowStatusUser_ToolTip
    {
        public Nullable<int> FADID { get; set; }
        public string RoleName { get; set; }
        public string ServiceNo { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public Nullable<int> FMSID { get; set; }
        public int FADFID { get; set; }
        public int RID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
