//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_F121
    {
        public int CHID { get; set; }
        public int ChargeNo { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public string Sno { get; set; }
        public string ServiceNo { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public int Expr1 { get; set; }
        public Nullable<int> OffenceTypeId { get; set; }
        public string OffenceName { get; set; }
        public string OffenceWASO { get; set; }
        public string OffencePlace { get; set; }
        public Nullable<System.DateTime> OffenceDate { get; set; }
        public string OffenceSection { get; set; }
        public Nullable<int> PunishableSection { get; set; }
        public Nullable<int> FPIID { get; set; }
        public Nullable<System.DateTime> PunishDate { get; set; }
        public Nullable<int> PunishmentID { get; set; }
        public string Appointment { get; set; }
        public string PunishmentDescription { get; set; }
        public Nullable<short> Active { get; set; }
        public string CreateLocation { get; set; }
    }
}
