//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_GSQDetails
    {
        public string Rank { get; set; }
        public string Name { get; set; }
        public string Branch { get; set; }
        public string PostedLocation { get; set; }
        public string Division { get; set; }
        public Nullable<int> service_type { get; set; }
        public Nullable<int> RecordStatusID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FlowManagementStatusID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> FSGSQID { get; set; }
        public Nullable<int> RejectStatus { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
        public Nullable<int> SubmitStatus { get; set; }
        public int GSQHID { get; set; }
        public string Sno { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public string Location { get; set; }
        public string GSQLocation { get; set; }
        public string GSQNo { get; set; }
        public string GSQStatus { get; set; }
        public Nullable<System.DateTime> AllocatedDate { get; set; }
        public Nullable<System.DateTime> VacantDate { get; set; }
        public Nullable<System.DateTime> PORDate { get; set; }
        public string RefNo { get; set; }
        public Nullable<int> Active { get; set; }
        public string StatusName { get; set; }
    }
}
