//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_LeavePlan
    {
        public Nullable<int> LeaveCategoryID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> TotalLeaveMonth { get; set; }
        public Nullable<int> TotalLeaveDays { get; set; }
        public string LeaveCategoryName { get; set; }
        public string LeaveCategoryShortName { get; set; }
        public Nullable<int> Active { get; set; }
        public int ALPID { get; set; }
    }
}
