//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_LeaveP3Details
    {
        public string ServiceNo { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public string EstablishmentId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string IteamShortName { get; set; }
        public Nullable<decimal> CalAmount { get; set; }
        public Nullable<int> IsProcessed { get; set; }
        public Nullable<int> ItemsCode { get; set; }
        public int LHID { get; set; }
        public Nullable<int> service_type { get; set; }
        public Nullable<int> IteamCode { get; set; }
        public Nullable<int> DaysCounts { get; set; }
        public string Authority { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> LeaveProcessDate { get; set; }
    }
}
