//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_LivingStatusReject
    {
        public int LIOHID { get; set; }
        public Nullable<long> Sno { get; set; }
        public Nullable<int> LivingStatusID { get; set; }
        public string LivingStatusName { get; set; }
        public string Location { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public string RefNo { get; set; }
        public string Authority { get; set; }
        public Nullable<int> IsNOKChange { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> LIActive { get; set; }
        public string NOKAddress { get; set; }
        public string NOKName { get; set; }
        public string NOKChangeTo { get; set; }
        public string Expr1 { get; set; }
        public string District { get; set; }
        public string GSDivision { get; set; }
        public string NearestTown { get; set; }
        public string PoliceStation { get; set; }
        public Nullable<int> Active { get; set; }
        public string ServiceNo { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
        public Nullable<int> RejectStatus { get; set; }
        public Nullable<int> SubmitStatus { get; set; }
        public int FMSID { get; set; }
    }
}
