//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_LeaveFlow_FullDetails
    {
        public int LHID { get; set; }
        public string Sno { get; set; }
        public string EstablishmentId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<int> IsProcessed { get; set; }
        public Nullable<int> LeaveCategoryId { get; set; }
        public string ServiceNo { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public string Authority { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> RecordStatusId { get; set; }
        public string RecordStatusName { get; set; }
    }
}
