//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MQDetails
    {
        public int InOut_ID { get; set; }
        public string Sno { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public string Location { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public string Qurter_ID { get; set; }
        public string QurtersStatus { get; set; }
        public string QuarterLocation { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
