//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_NOKChangeDetails
    {
        public Nullable<int> RecordStatusID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FlowManagementStatusID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string NOKAddress { get; set; }
        public string NOKName { get; set; }
        public string NOKChangeTo { get; set; }
        public string District { get; set; }
        public string GSDivision { get; set; }
        public string NearestTown { get; set; }
        public string PoliceStation { get; set; }
        public string Authority { get; set; }
        public string Remarks { get; set; }
        public string EstablishmentId { get; set; }
        public Nullable<int> RejectStatus { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
        public Nullable<int> SubmitStatus { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public string Marriage_Status { get; set; }
        public string ServiceNo { get; set; }
        public Nullable<long> Sno { get; set; }
        public int NOKCHID { get; set; }
        public string Location { get; set; }
        public Nullable<int> NOKStatus { get; set; }
        public Nullable<System.DateTime> PORDate { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
