//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_PorReport
    {
        public string ServiceNo { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public string LeaveCategoryName { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public string LivingStatusShortName { get; set; }
        public Nullable<decimal> Weekend { get; set; }
        public Nullable<int> PublicHoliday { get; set; }
        public Nullable<int> AnnualLeave { get; set; }
        public Nullable<int> PrivilegeLeave { get; set; }
        public Nullable<int> CasualLeave { get; set; }
        public Nullable<int> LeaveLeave { get; set; }
        public Nullable<int> ReEngagementLeave { get; set; }
        public string Authority { get; set; }
        public int RID { get; set; }
        public string RoleName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string EstablishmentId { get; set; }
        public Nullable<int> service_type { get; set; }
        public int LHID { get; set; }
        public int LDID { get; set; }
        public int LCID { get; set; }
        public int LFSID { get; set; }
        public Nullable<int> LSID { get; set; }
        public int FMSID { get; set; }
    }
}
