//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_P2Marriage
    {
        public string SNo { get; set; }
        public string ServiceNo { get; set; }
        public string SpouseName { get; set; }
        public string NICNo { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public string MarriageCertificateNo { get; set; }
        public string MarrigeId { get; set; }
    }
}
