//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_PersonalDetail
    {
        public string SNo { get; set; }
        public string ServiceNo { get; set; }
        public Nullable<int> RankID { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public string Branch { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string PostedLocation { get; set; }
        public string Division { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public int type { get; set; }
        public Nullable<int> Service_Status { get; set; }
        public string Marriage_Status { get; set; }
        public Nullable<int> service_type { get; set; }
        public Nullable<System.DateTime> DateOfEnlist { get; set; }
        public string Formation { get; set; }
        public Nullable<int> SubRank { get; set; }
        public string serTypeDescription { get; set; }
    }
}
