//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Punishments
    {
        public int PunishmentID { get; set; }
        public string Punishment { get; set; }
        public int PunishTypeID { get; set; }
        public int Status { get; set; }
        public Nullable<int> DelayPeriod { get; set; }
    }
}
