//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_RANKS
    {
        public int RANK { get; set; }
        public string RNK_NAME { get; set; }
        public Nullable<int> RANK_TYPE { get; set; }
        public string SHORT_NAME { get; set; }
        public string LONG_NAME { get; set; }
        public Nullable<int> SENIORITY { get; set; }
        public Nullable<int> PROMO_DURATION { get; set; }
        public Nullable<int> TOTAL_SERVICE_FOR_PROMOTION { get; set; }
        public Nullable<decimal> TOTAL_SERVICE_FOR_PROMOTION_DE_LAC { get; set; }
        public Nullable<decimal> TOTAL_SERVICE_FOR_PROMOTION_DE_ACPL { get; set; }
        public string TEMPORY_SUBSTANTIVE { get; set; }
        public Nullable<int> RankGroup { get; set; }
        public string AppProm { get; set; }
        public string AppPromType { get; set; }
        public string NextAppProm { get; set; }
        public string PromPaid { get; set; }
        public Nullable<decimal> TOTAL_SERVICE_FOR_PROMOTION_DE { get; set; }
    }
}
