//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_SelectUserRole
    {
        public string UserName { get; set; }
        public string RoleName { get; set; }
        public string LocationId { get; set; }
        public string ServiceNo { get; set; }
    }
}
