//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_UpdateQuery
    {
        public int LFSID { get; set; }
        public Nullable<int> LeaveHeaderId { get; set; }
        public Nullable<int> FMSID { get; set; }
        public Nullable<int> RecordStatusId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
        public int LHID { get; set; }
        public Nullable<int> ServiceCategoryId { get; set; }
        public string Sno { get; set; }
        public Nullable<int> LeaveCategoryId { get; set; }
        public string EstablishmentId { get; set; }
        public string DeivisionId { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<int> PrivilegeLeave { get; set; }
        public Nullable<int> AnnualLeave { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Authority { get; set; }
        public Nullable<int> PorStatus { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<System.DateTime> Expr2 { get; set; }
        public string Expr3 { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public Nullable<System.DateTime> Expr5 { get; set; }
        public string Expr6 { get; set; }
        public Nullable<int> Expr7 { get; set; }
        public Nullable<int> IsProcessed { get; set; }
    }
}
